name: Receive repository dispatch event

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [test_dispatch-event]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Event received
        run: echo "Event received"